### ISSUE TITLE
Local build failing

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis.io#166]
I'm trying to execute locally the website and I'm getting the following error as sun as I run `gulp` command:
```
SYNDESIS is now running on port 7000
Watching for changes...
[16:05:03] Finished 'js' after 268 ms
Building sites … ERROR 2020/04/20 16:05:02 Failed to add template "index.html" in path "/home/squake/workspace/syndesis.io/layouts/index.html": template: /home/squake/workspace/syndesis.io/layouts/index.html:5: function "hugo" not defined
ERROR 2020/04/20 16:05:02 Failed to add template "theme/_default/single.html" in path "/home/squake/workspace/syndesis.io/themes/syndesis/layouts/_default/single.html": template: /home/squake/workspace/syndesis.io/themes/syndesis/layouts/_default/single.html:5: function "hugo" not defined
ERROR 2020/04/20 16:05:02 Failed to add template "theme/blog/list.html" in path "/home/squake/workspace/syndesis.io/themes/syndesis/layouts/blog/list.html": template: /home/squake/workspace/syndesis.io/themes/syndesis/layouts/blog/list.html:5: function "hugo" not defined
ERROR 2020/04/20 16:05:02 Failed to add template "theme/blog/single.html" in path "/home/squake/workspace/syndesis.io/themes/syndesis/layouts/blog/single.html": template: /home/squake/workspace/syndesis.io/themes/syndesis/layouts/blog/single.html:5: function "hugo" not defined
ERROR 2020/04/20 16:05:02 Failed to add template "theme/docs/list.html" in path "/home/squake/workspace/syndesis.io/themes/syndesis/layouts/docs/list.html": template: /home/squake/workspace/syndesis.io/themes/syndesis/layouts/docs/list.html:5: function "hugo" not defined
ERROR 2020/04/20 16:05:02 Failed to add template "theme/docs/single.html" in path "/home/squake/workspace/syndesis.io/themes/syndesis/layouts/docs/single.html": template: /home/squake/workspace/syndesis.io/themes/syndesis/layouts/docs/single.html:5: function "hugo" not defined
ERROR 2020/04/20 16:05:02 Failed to add template "theme/partials/docs/sidenav.html" in path "/home/squake/workspace/syndesis.io/themes/syndesis/layouts/partials/docs/sidenav.html": template: /home/squake/workspace/syndesis.io/themes/syndesis/layouts/partials/docs/sidenav.html:5: function "hugo" not defined
Total in 98 ms

Error: Error building site: logged 7 error(s)

[16:05:03] 'hugo:serve' errored after 307 ms
[16:05:03] Error: Command failed: hugo serve --port 7000 --bind 0.0.0.0
Error: Error building site: logged 7 error(s)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[16:05:03] 'default' errored after 309 ms
[16:05:03] The following tasks did not complete: css, watch, <anonymous>
[16:05:03] Did you forget to signal async completion?
```
Did the procedure to execute the website change or is it a bug?

**Comment by squakez** [comment]
@kahboom, @gashcrumb would you mind having a look?

**Comment by squakez** [comment]
Nevermind, as we've already discussed it seems I have an outdated version of required `hugo` generator. I will add some note on the readme to reflect it.
